name: Rebase PR

on:
  issue_comment:
    types: [created]

jobs:
  do_rebase:
    runs-on: ubuntu-20.04
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Github context
        env:
          ASDF: ${{ toJson(github.event) }}
        run: echo "HELLO"

      - name: Rebase
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          PR_NUM: "6"
          GH_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          python3 .github/scripts/tryrebase.py "${PR_NUM}"
